### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by PetteriAimonen** [xbarin02/libdwt#1]
The current license (BUT OPEN SOURCE LICENCE) makes using libdwt very difficult, both in open source and in closed source applications.

If I read it correctly, it appears to be a copyleft license, like GPL. That's fine by itself, but as written, it seems GPL-incompatible.

Do I understand correctly that it is prohibited to combine libdwt with GPL code?

Would it be possible to relicense or dual license under some OSI-approved open source license (https://opensource.org/licenses)?

**Comment by xbarin02** [comment]
He Petteri,

I have changed the license to the MIT License. Hopefully it will help you.

Best wishes,

David Barina

**Comment by PetteriAimonen** [comment]
Great, thanks a lot!
